### ISSUE TITLE
Infinite Curvature in exactly straight paths

### ISSUE THREAD

**Issue by tarinimaram** [mjansen4857/pathplannerlib#1]
When designing a path that is exactly straight (same x-values or same y-values for starting and ending point), the curvature that is calculated for each state is Infinity, which messes up the calculation for wheel speeds (set to NaN). This makes the robot have uncontrolled wheel speeds. 
The attached text file is the path that we were having issues with which is an exactly straight horizontal line. 
The csv file shows values from each generated state -  note how curvature is Infinity for each state. 
[MoveForwards.csv](https://github.com/mjansen4857/pathplannerlib/files/7901582/MoveForwards.csv)
[MoveForwards.txt](https://github.com/mjansen4857/pathplannerlib/files/7901596/MoveForwards.txt)

**Comment by mjansen4857** [comment]
Fixed this in 1cdda0f and released it in v2022.1.0

This is not yet fixed in the GUI generator however.
