### ISSUE TITLE
No C++ doxygen documentation?

### ISSUE THREAD

**Issue by virtuald** [mjansen4857/pathplannerlib#7]
Do you have plans to add doxygen documentation to the C++ headers? It's all pretty bare right now.

RobotPy autogenerates typestubs and documentation from the doxygen, so at the moment it looks like this: https://robotpy.readthedocs.io/projects/pathplannerlib/en/stable/pathplannerlib/GeometryUtil.html#pathplannerlib.GeometryUtil :cry:

**Comment by mjansen4857** [comment]
Definitely. I have wanted to for a while but never got around to it. I'll start putting some in now.

**Comment by mjansen4857** [comment]
Ok I added some for the methods meant to be used by the end user for now, everything else I'll get around to at some point when I refactor some things for next season.

**Comment by virtuald** [comment]
Thanks! Any chance you can push an updated release with that? Currently we pull from the sources in your vendordep repo.

**Comment by mjansen4857** [comment]
I didn't push a whole new release but I updated the sources and headers zip files with a new build so if you pull those down again it should have the docs.
