### ISSUE TITLE
Enable Windows builds

### ISSUE THREAD

**Issue by emmaworley** [mjansen4857/pathplannerlib#8]
It is not possible to use pathplannerlib in simulation on Windows. Would it be possible to enable Windows builds to support this usecase?

**Comment by mjansen4857** [comment]
I've tried and will keep trying lol. When trying to build it on windows it gives me a useless error message that I need to track down somehow. Some dependency is missing but I have no idea what it is. Hopefully I can figure it out before next year.

**Comment by emmaworley** [comment]
Mind if I try to get it working?

**Comment by mjansen4857** [comment]
If you can that would be awesome. I've tried 3 different systems with various levels of software installed so far and have had no luck.

**Comment by mjansen4857** [comment]
Whelp it looks like I figured it out. There was some gradle configuration that needed to be added that wasn't in the vendor template. I'll work on pushing windows builds real quick

**Comment by mjansen4857** [comment]
Ok I uploaded desktop builds for windows and linux to the current version. I think you'll have to uninstall the library and add it from the json link again since the json file changed. Can you confirm simulation works for you before I close this?

**Comment by emmaworley** [comment]
Yes, will test later today.

**Comment by emmaworley** [comment]
Seems to be building and running successfully.
